# Generated by Django 4.0.3 on 2022-04-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_contact_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
