# Generated by Django 4.0.3 on 2022-04-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_contact_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.URLField(blank=True, null=True),
        ),
    ]
